FROM microsoft/dotnet:1.1-sdk

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g yarn

WORKDIR /app
ENV ASPNETCORE_URLS http://*:5000
ENV ASPNETCORE_ENVIRONMENT Staging
EXPOSE 5000
COPY . /app
COPY ./appsettings.staging.json /app/appsettings.json

RUN dotnet restore

RUN yarn
RUN node_modules/.bin/webpack
RUN node_modules/.bin/gulp

RUN dotnet bundle
CMD [ "dotnet", "run"]
